language: node_js

node_js:
  - "11.4.0"

sudo: required

services:
  - docker

after_deploy:
  - echo "Done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "$REGION"
  app: "hkuf-backbone"
  env: "$ENV"
  bucket_name: "$BUCKETNAME"
  on:
    branch: master
